In [2]:
import pandas as pd

In [6]:
import torch
from sentence_transformers import SentenceTransformer

print(f"Using GPU: {torch.cuda.is_available()}")
model = SentenceTransformer('all-MiniLM-L6-v2', device='cuda')
print("Model loaded on RTX 4050 successfully!")

Using GPU: True

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4437.87it/s]

Model loaded on RTX 4050 successfully!

In [3]:
df = pd.read_csv('dataset/synthetic_logs.csv')
df

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert
...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert

In [4]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [5]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN 
import numpy as np

c:\Users\shifa\Desktop\Projects\classification_logs\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:

embeddings = model.encode(df['log_message'].tolist())
embeddings[:2]

array([[-1.02939658e-01,  3.35459076e-02, -2.20260322e-02,
         1.55102310e-03, -9.86923371e-03, -1.78956211e-01,
        -6.34410307e-02, -6.01761937e-02,  2.81108450e-02,
         5.99620566e-02, -1.72618628e-02,  1.43368531e-03,
        -1.49560064e-01,  3.15292412e-03, -5.66030703e-02,
         2.71686260e-02, -1.49890119e-02, -3.54037806e-02,
        -3.62936333e-02, -1.45409480e-02, -5.61491353e-03,
         8.75538364e-02,  4.55120653e-02,  2.50963047e-02,
         1.00187324e-02,  1.24266408e-02, -1.39923513e-01,
         7.68695921e-02,  3.14095058e-02, -4.15245118e-03,
         4.36902493e-02,  1.71249919e-02, -8.00950900e-02,
         5.74005917e-02,  1.89092699e-02,  8.55261907e-02,
         3.96399312e-02, -1.34371817e-01, -1.44365174e-03,
         3.06709413e-03,  1.76854104e-01,  4.44887439e-03,
        -1.69274583e-02,  2.24267114e-02, -4.35049571e-02,
         6.09026384e-03, -9.98170208e-03, -6.23972826e-02,
         1.07372338e-02, -6.04890706e-03, -7.14661106e-02,
        -8.45809747e-03, -3.18019912e-02, -1.00518338e-01,
         2.25921438e-04, -1.89340953e-02, -3.17793600e-02,
         4.00861315e-02,  2.19178647e-02, -2.59528551e-02,
         5.84525466e-02, -8.12509805e-02,  2.12029032e-02,
        -5.02687655e-02,  1.32057434e-02,  1.32680498e-03,
         2.27062944e-02, -3.45793962e-02,  3.91547084e-02,
        -2.09434330e-02,  3.24818958e-03,  4.43960764e-02,
        -9.85358283e-02, -2.88895853e-02, -6.85022026e-03,
         5.38819171e-02,  6.46109954e-02, -2.45060418e-02,
         9.21829045e-02, -7.49869794e-02,  1.23995245e-02,
        -1.00026600e-01, -4.64910530e-02,  6.01570606e-02,
        -2.46480275e-02, -7.08076060e-02, -2.77270600e-02,
         9.72609967e-02,  3.85842510e-02, -1.44292004e-02,
        -7.46875303e-04, -1.04305493e-02, -1.61842536e-02,
         4.43627611e-02,  9.26002674e-03,  7.14165717e-02,
         6.37917444e-02,  4.94930744e-02, -6.02568202e-02,
         4.04805951e-02, -3.42860967e-02, -1.93881076e-02,
         6.61234036e-02,  6.01589493e-02,  1.09370500e-02,
        -5.38625428e-03,  1.44580016e-02,  9.25430357e-02,
        -3.14563885e-02, -1.84351895e-02,  9.91874654e-03,
        -1.85574684e-02,  1.31280452e-03,  2.26234351e-05,
         2.02734210e-03,  2.75256690e-02, -4.81927022e-02,
         5.42825423e-02, -7.32066482e-02,  4.88667041e-02,
         4.98490445e-02, -9.01141018e-03, -4.68905717e-02,
        -4.25887033e-02, -8.19523707e-02,  3.87105830e-02,
         7.85502642e-02,  1.46077184e-32,  1.66707058e-02,
         5.25493808e-02, -1.82448979e-02, -1.26685752e-02,
         6.52837530e-02, -2.11777352e-02, -4.06323001e-02,
         4.14947644e-02, -2.48362310e-02, -1.33068832e-02,
        -5.46753965e-02, -5.99112886e-04, -4.89246938e-03,
        -6.27359822e-02, -3.84878144e-02, -6.13543764e-02,
         8.27405304e-02,  2.34380439e-02, -8.63089506e-03,
         1.31002869e-02,  6.44215122e-02, -4.41361293e-02,
        -6.98632821e-02, -7.36060217e-02, -4.33264188e-02,
         6.96524838e-03, -5.05956896e-02, -1.60912015e-02,
        -5.66793121e-02,  3.35456640e-03,  5.34114949e-02,
         2.47761197e-02, -1.47986244e-02, -2.93242894e-02,
         7.30228424e-02, -1.86833516e-02,  8.13136771e-02,
        -2.69967746e-02, -5.68056516e-02, -6.59388676e-02,
        -5.95392985e-03,  2.85312831e-02, -7.85358027e-02,
        -2.76697101e-03, -3.26468050e-03, -9.28333327e-02,
        -7.27363005e-02, -3.31903733e-02,  1.01411290e-01,
         9.79881808e-02, -9.78740677e-02,  1.98668279e-02,
         2.38836538e-02, -1.81672927e-02, -3.73709351e-02,
         1.96546479e-03,  6.34425730e-02,  1.18271522e-02,
        -1.12040918e-02, -3.87316719e-02,  9.32424441e-02,
         4.26635146e-03, -1.66872758e-02, -6.87463805e-02,
         1.55119635e-02, -4.97755259e-02,  3.34492698e-02,
         8.00032169e-02,  2.12282240e-02,  1.34581879e-01,
        -2.30729822e-02,  5.53859472e-02,  3.07557881e-02,
        -2.93905791e-02,  2.31905598e-02, -9.34307426e-02,
         7.58034587e-02, -5.21205924e-03, -5.14523461e-02,
         3.32688838e-02,  3.67963500e-02, -1.06450431e-02,
         1.01634767e-02, -2.07650270e-02, -5.85518815e-02,
         4.79328744e-02,  2.13694163e-02,  8.76213014e-02,
         3.35499877e-03, -3.80336344e-02, -1.81205310e-02,
         6.87439553e-03,  5.15879095e-02, -4.75599058e-02,
        -6.12065196e-02, -1.45483677e-32,  4.12797881e-03,
         4.59634745e-03, -5.63900694e-02,  4.32464620e-03,
        -1.09446363e-03,  9.31951962e-03, -2.20269207e-02,
         5.79564422e-02, -1.44787626e-02,  4.64155413e-02,
         1.43542916e-01, -6.89755902e-02,  6.09631427e-02,
        -8.93743709e-02,  2.40918938e-02,  2.06010342e-02,
        -2.82416232e-02, -6.48316070e-02,  5.64795695e-02,
        -7.48341996e-03, -3.52057591e-02,  8.51060823e-02,
         1.30359745e-02,  2.02258509e-02, -1.44390929e-02,
        -4.63718809e-02,  1.77209787e-02,  1.59106050e-02,
        -9.51009318e-02, -3.54527459e-02,  2.08695810e-02,
         3.84385465e-03, -8.77918601e-02,  6.44575804e-02,
         1.44170495e-02,  3.84729356e-03,  4.70991619e-02,
         4.94661406e-02,  1.53861968e-02, -2.59579085e-02,
         9.10895243e-02,  1.83307473e-02, -5.89207113e-02,
         2.51992904e-02, -3.30373943e-02,  8.23345259e-02,
         1.74792111e-02,  6.48047403e-02, -1.19673656e-02,
        -3.31777968e-02,  3.00177634e-02,  3.54220122e-02,
        -1.39624570e-02,  6.69272169e-02,  3.87919806e-02,
         6.06917106e-02,  1.17967324e-03, -2.38786265e-02,
        -1.26930416e-01,  1.13847200e-02,  1.59290396e-02,
        -1.29426625e-02, -8.63247663e-02,  8.53657164e-03,
         6.03760667e-02,  1.51122576e-02, -1.19132347e-01,
         1.15235336e-02,  5.97089082e-02, -3.93346585e-02,
         1.55673549e-02,  1.04602035e-02, -4.72456254e-02,
        -2.59243306e-02,  9.98529978e-03,  3.07146627e-02,
        -7.14843720e-02,  6.98957639e-03, -1.55132441e-02,
         2.18863934e-02, -2.78145541e-02,  6.92733005e-02,
        -2.75903307e-02,  2.62429044e-02,  3.52563225e-02,
        -4.26420346e-02,  7.46361562e-04,  6.59866929e-02,
        -5.15105799e-02, -3.58433574e-02, -6.53454335e-03,
        -2.75858659e-02, -1.00125462e-01,  7.83325657e-02,
        -1.45799201e-02, -6.18457676e-08,  2.00325046e-02,
         6.59785867e-02, -2.04702727e-02,  1.64043885e-02,
         7.63001516e-02,  7.32182637e-02,  5.65794855e-03,
        -6.97731739e-04, -3.63796577e-03,  6.02394305e-02,
        -3.27187628e-02, -6.45838454e-02, -5.97952940e-02,
        -1.76695120e-02,  6.10141922e-03, -5.63484570e-03,
        -1.22972235e-01,  6.35818839e-02, -2.19432414e-02,
        -1.16406478e-01,  2.34365351e-02, -7.23524839e-02,
         2.31774375e-02, -6.55987188e-02, -7.42682591e-02,
         2.60145608e-02,  3.59757878e-02,  7.68433064e-02,
        -3.08057535e-02, -2.34794132e-02, -6.30426630e-02,
        -3.62157263e-02, -1.03560034e-02, -4.75602038e-02,
        -2.87522543e-02,  2.96401326e-02, -5.26895234e-03,
         5.67889996e-02, -3.74486903e-03,  3.09611876e-02,
         3.48227248e-02,  3.78607363e-02,  2.10155733e-02,
         2.70691551e-02,  5.25520667e-02,  7.16229379e-02,
        -5.53757604e-03,  4.01094146e-02,  5.16276099e-02,
        -2.67314520e-02,  5.94223477e-02, -4.29223888e-02,
        -1.19760847e-02,  3.05985902e-02, -7.40331858e-02,
         1.84221938e-02, -8.64863582e-03, -8.83557945e-02,
        -5.91983944e-02, -1.00866026e-04,  1.12913705e-01,
         4.57789237e-03, -4.25971188e-02,  3.22619989e-03],
       [ 8.04573391e-03, -3.57392319e-02,  4.93874028e-02,
        -7.19186151e-03,  6.17681711e-04, -9.05684605e-02,
         5.75595275e-02, -4.39446084e-02,  1.74751170e-02,
         5.21202870e-02, -4.62332182e-02,  2.49038953e-02,
         4.80810888e-02,  6.86636493e-02,  3.56146656e-02,
         3.00088730e-02,  2.61450093e-02, -9.05241519e-02,
        -8.02173689e-02,  5.04851006e-02, -7.90870562e-02,
        -1.76852068e-03, -2.48927847e-02,  9.02152732e-02,
         5.83698181e-03, -6.91070855e-02, -6.67965636e-02,
        -6.99113635e-03, -1.04566023e-01, -2.66474169e-02,
         3.05640213e-02,  2.02933885e-02,  2.25454811e-02,
        -4.22686618e-03,  1.11173606e-02,  6.78261518e-02,
         1.06074074e-02,  7.56635591e-02, -8.22777748e-02,
         8.45730677e-03, -6.97612241e-02, -4.21973839e-02,
        -1.05674425e-02,  2.23672949e-02,  5.64497039e-02,
         8.16500932e-03,  1.09344050e-01,  3.16564664e-02,
        -1.76923666e-02, -3.21071297e-02, -3.39975916e-02,
        -4.91820916e-04,  3.72876017e-03,  2.83771548e-02,
        -1.28521482e-02, -1.07928505e-03, -6.32419214e-02,
         6.89900666e-02,  1.77270863e-02, -5.20959646e-02,
         8.28308053e-03,  5.45032471e-02, -5.42099513e-02,
        -4.53332923e-02, -4.07494046e-02, -2.82698646e-02,
         1.23605551e-02, -2.13816501e-02, -2.36266088e-02,
         1.25318076e-02, -2.37170830e-02,  3.97411510e-02,
        -1.24362230e-01,  7.60625526e-02,  5.50833605e-02,
         8.28216597e-02,  2.97118966e-02, -1.84067488e-02,
        -1.96194816e-02,  5.54318987e-02, -3.49143818e-02,
        -4.14678305e-02, -3.37047577e-02,  7.31324479e-02,
         4.41836566e-02,  2.55246796e-02, -8.26408248e-03,
        -1.07323704e-02, -4.26243581e-02, -2.84963404e-03,
         7.38559216e-02,  2.27768086e-02,  7.15384493e-04,
         4.36011963e-02,  5.09079844e-02,  6.38482273e-02,
        -2.73155440e-02, -6.55021966e-02, -7.69265443e-02,
         3.55171300e-02,  9.60494131e-02,  2.18195487e-02,
         1.20155104e-02, -1.17863361e-02, -4.57927259e-03,
        -8.58035032e-03,  3.37150171e-02,  2.31918246e-02,
        -7.58325383e-02, -5.23878708e-02,  4.53934111e-02,
        -3.80785502e-02, -3.34905125e-02,  9.20352936e-02,
         2.87688747e-02, -3.33817340e-02, -1.95854413e-03,
        -3.04582034e-04, -1.70499235e-02,  2.85335481e-02,
        -8.81096497e-02, -4.02253084e-02, -4.00093757e-02,
        -1.03193093e-02, -2.51968242e-02,  2.14092638e-02,
         1.31045282e-01, -5.29635189e-34, -1.09651700e-01,
         1.29811810e-02,  5.92659228e-03,  4.73506525e-02,
        -8.60294234e-03, -3.67089361e-02,  3.05214990e-02,
         5.53066470e-02, -4.71985191e-02, -1.25118969e-02,
        -1.15366392e-01,  9.08000302e-03,  1.07346520e-01,
        -4.94735017e-02, -1.34290894e-02, -4.61562127e-02,
         2.45320499e-02,  9.45082307e-03,  2.04323512e-02,
        -3.99918780e-02, -4.67826165e-02,  2.21171286e-02,
        -4.58186679e-02, -8.13272223e-03, -7.65669998e-03,
         1.92284361e-02,  4.85845394e-02, -2.55903304e-02,
         1.61545025e-03, -1.37180313e-02,  9.67306644e-03,
         7.36415759e-03,  1.14088571e-02,  1.28853485e-01,
         7.71834981e-03,  7.06362501e-02,  2.54452154e-02,
         4.06523831e-02,  2.44039688e-02,  1.43776750e-02,
        -6.00932650e-02,  7.38180354e-02, -2.44700704e-02,
         8.98901597e-02,  3.17052007e-03,  1.01834476e-01,
         4.17742059e-02, -5.95177822e-02, -3.23181264e-02,
         3.80938686e-02,  1.21155037e-02, -4.07834314e-02,
         2.84823086e-02,  4.90988642e-02, -9.35704447e-03,
         6.50073886e-02,  7.23532215e-02, -1.67793203e-02,
        -8.22416041e-03, -1.61573309e-02,  5.96225336e-02,
        -3.36083658e-02,  2.12108325e-02, -6.06090575e-02,
         1.54377654e-01, -7.24145845e-02, -3.77272852e-02,
        -3.26890238e-02, -1.80381408e-03, -1.01960255e-02,
        -1.60678616e-03, -6.91846684e-02,  8.28445256e-02,
         9.88839939e-02,  3.45468754e-03, -9.90247577e-02,
        -3.52826901e-02, -7.13178962e-02, -4.96000126e-02,
        -3.43954973e-02, -8.13042298e-02,  4.81448062e-02,
         5.00684232e-03, -2.21499782e-02, -5.60056306e-02,
         1.00067323e-02, -3.59794013e-02,  1.06184363e-01,
        -4.54196259e-02,  7.16393664e-02, -2.36773230e-02,
         9.98144783e-03,  2.73601897e-02,  1.05985448e-01,
         4.60163318e-02,  9.59029178e-34, -1.12306938e-01,
         2.78912298e-02, -3.35901007e-02,  5.39242588e-02,
        -2.22291648e-02,  1.53769413e-02,  3.10411267e-02,
         3.39011289e-02,  7.43166879e-02,  3.42471078e-02,
        -3.35054263e-03, -2.05350760e-02, -3.62370014e-02,
         2.29334123e-02, -3.01992334e-02, -1.00819916e-01,
         3.29193994e-02,  6.77542984e-02,  1.35645326e-02,
        -5.20545198e-03, -6.58158362e-02,  9.54550430e-02,
        -1.34038636e-02,  1.53885726e-02, -7.22936094e-02,
         9.67835709e-02, -8.08119401e-02, -4.53453325e-03,
        -6.42011836e-02, -4.99278381e-02,  4.64197919e-02,
         2.21341085e-02,  3.13109346e-02,  9.13568586e-02,
        -4.61119786e-02, -1.02761090e-01,  3.04415952e-02,
         5.09876348e-02,  6.70141056e-02,  1.04042655e-02,
         1.63533464e-02,  3.92030887e-02,  2.17154063e-02,
         5.36603145e-02,  3.62809673e-02, -4.22140248e-02,
        -2.47226637e-02,  1.90311801e-02,  3.61724198e-02,
         6.37021065e-02, -3.21581750e-03, -8.50390270e-03,
         3.94655317e-02,  9.02656000e-03,  1.93095729e-02,
         6.60718009e-02,  1.02694947e-02, -4.43853885e-02,
        -1.56523455e-02, -1.55714592e-02,  1.32904444e-02,
        -1.16108339e-02,  4.21832167e-02, -5.44777103e-02,
         1.29237190e-01, -2.25756615e-02,  5.26203848e-02,
        -1.58437025e-02,  9.33165625e-02,  6.38025859e-03,
        -9.36161820e-03, -6.08876050e-02, -3.27307768e-02,
        -3.44816446e-02,  3.29974107e-02, -4.79391702e-02,
        -9.81300697e-02,  2.91164946e-02, -2.70903353e-02,
         1.81867406e-02, -1.73860192e-02, -4.40371446e-02,
        -7.97001943e-02,  3.01647130e-02, -6.35260493e-02,
         1.25963474e-02,  8.50250721e-02, -4.58910540e-02,
         5.81017397e-02, -2.71002203e-02,  8.42775926e-02,
        -4.09972928e-02, -3.37655954e-02,  1.02088209e-02,
        -2.54192818e-02, -1.40610323e-08,  4.94446494e-02,
        -9.04357061e-02, -6.06710017e-02,  8.29528943e-02,
        -3.29032876e-02,  4.14910577e-02,  9.99591406e-03,
         6.96135825e-03,  3.99230001e-03, -3.24333534e-02,
        -3.14657390e-02, -5.33160940e-02, -3.80912945e-02,
         1.62077043e-02,  2.45778374e-02, -7.26419389e-02,
        -6.56893402e-02, -8.23131651e-02, -8.00500885e-02,
        -5.36649525e-02,  5.60894459e-02, -1.10913105e-02,
         9.62130027e-04, -1.22690290e-01, -5.13836667e-02,
         9.96703096e-03,  1.00696282e-02,  1.07073061e-01,
         1.19758174e-02,  1.00423563e-02, -6.28261641e-02,
        -7.49696866e-02, -6.34075701e-03, -2.72201318e-02,
        -1.28096193e-01, -2.62459964e-02, -1.81464311e-02,
        -9.85359997e-02, -3.02990600e-02, -4.02615182e-02,
         9.94290784e-02,  5.35999909e-02,  2.74899527e-02,
        -5.53683145e-03,  8.43571201e-02,  8.35161880e-02,
         3.74305062e-02,  7.11937174e-02,  2.98902709e-02,
         2.32728720e-02, -3.62112485e-02,  6.20539747e-02,
         2.15148162e-02,  5.19732237e-02,  1.45337647e-02,
        -4.60966453e-02,  5.02553992e-02, -7.27027580e-02,
         2.92778797e-02,  5.62663153e-02, -3.86354961e-02,
         1.53831542e-02, -6.23094887e-02, -2.77466476e-02]], dtype=float32)

In [1]:
import torch

print(f"PyTorch Version: {torch.__version__}")
print(f"CUDA Available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not detected by PyTorch.")

PyTorch Version: 2.5.1+cu121
CUDA Available: True
GPU Name: NVIDIA GeForce RTX 4050 Laptop GPU

In [11]:
dbscan = DBSCAN(eps=0.2,min_samples =2,metric='cosine')
clusters = dbscan.fit_predict(embeddings)

df['cluster'] = clusters

In [13]:
df.cluster.unique()
df[df.cluster == 1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,bert,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,bert,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,bert,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,bert,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,bert,1
816,7/9/2025 9:38,BillingSystem,Error in email delivery affected service,Critical Error,bert,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,bert,1
1011,2/9/2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,bert,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,bert,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,bert,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,bert,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,bert,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,bert,1
1176,10/1/2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,bert,1
1189,2/9/2025 6:15,ModernCRM,Service issue caused by email delivery error,Critical Error,bert,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,bert,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,bert,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,bert,1
1453,9/11/2025 1:18,BillingSystem,Mail delivery error impacted email service,Critical Error,bert,1
1554,3/2/2025 9:21,ModernCRM,Email system had a difficulty sending messages,Error,bert,1
1567,5/11/2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,bert,1
1582,9/10/2025 9:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,bert,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,bert,1
1867,10/6/2025 11:04,ModernCRM,Email service had a sending malfunction,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1
1972,3/12/2025 3:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,bert,1
2049,10/1/2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,bert,1
2165,4/4/2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,bert,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,bert,1
2284,10/4/2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,bert,1
2312,3/9/2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,bert,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,bert,1
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1

In [14]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts>10].index

for cluster in large_clusters:
    print(f"Cluster {cluster}:")
    print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index = False))
    print()

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 30:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster -1:
Lead conversion failed for prospect ID 7842 due...
Attempt to access account Account3142 was not a...
Unrecoverable issue found in vital application ...
Non-recoverable fault detected in key applicati...
API endpoint 'getCustomerDetails' is deprecated...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 32:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 46:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 47:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 24:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 39:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 52:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 25:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

In [20]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern,label in regex_patterns.items():
        if re.search(pattern, log_message,re.IGNORECASE):
            return label
    return None

In [21]:
classify_with_regex("Backup 20:00:19.")

In [24]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [32]:
df_non_reg = df[df['regex_label'].isnull()].copy()
df_non_reg

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,NaN
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,NaN

In [34]:
df_non_legacy = df_non_reg[df_non_reg.source!='LegacyCRM']
df_non_legacy.source.unique()

<StringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [35]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings[:2]

array([[-1.02939658e-01,  3.35459076e-02, -2.20260322e-02,
         1.55102310e-03, -9.86923371e-03, -1.78956211e-01,
        -6.34410307e-02, -6.01761937e-02,  2.81108450e-02,
         5.99620566e-02, -1.72618628e-02,  1.43368531e-03,
        -1.49560064e-01,  3.15292412e-03, -5.66030703e-02,
         2.71686260e-02, -1.49890119e-02, -3.54037806e-02,
        -3.62936333e-02, -1.45409480e-02, -5.61491353e-03,
         8.75538364e-02,  4.55120653e-02,  2.50963047e-02,
         1.00187324e-02,  1.24266408e-02, -1.39923513e-01,
         7.68695921e-02,  3.14095058e-02, -4.15245118e-03,
         4.36902493e-02,  1.71249919e-02, -8.00950900e-02,
         5.74005917e-02,  1.89092699e-02,  8.55261907e-02,
         3.96399312e-02, -1.34371817e-01, -1.44365174e-03,
         3.06709413e-03,  1.76854104e-01,  4.44887439e-03,
        -1.69274583e-02,  2.24267114e-02, -4.35049571e-02,
         6.09026384e-03, -9.98170208e-03, -6.23972826e-02,
         1.07372338e-02, -6.04890706e-03, -7.14661106e-02,
        -8.45809747e-03, -3.18019912e-02, -1.00518338e-01,
         2.25921438e-04, -1.89340953e-02, -3.17793600e-02,
         4.00861315e-02,  2.19178647e-02, -2.59528551e-02,
         5.84525466e-02, -8.12509805e-02,  2.12029032e-02,
        -5.02687655e-02,  1.32057434e-02,  1.32680498e-03,
         2.27062944e-02, -3.45793962e-02,  3.91547084e-02,
        -2.09434330e-02,  3.24818958e-03,  4.43960764e-02,
        -9.85358283e-02, -2.88895853e-02, -6.85022026e-03,
         5.38819171e-02,  6.46109954e-02, -2.45060418e-02,
         9.21829045e-02, -7.49869794e-02,  1.23995245e-02,
        -1.00026600e-01, -4.64910530e-02,  6.01570606e-02,
        -2.46480275e-02, -7.08076060e-02, -2.77270600e-02,
         9.72609967e-02,  3.85842510e-02, -1.44292004e-02,
        -7.46875303e-04, -1.04305493e-02, -1.61842536e-02,
         4.43627611e-02,  9.26002674e-03,  7.14165717e-02,
         6.37917444e-02,  4.94930744e-02, -6.02568202e-02,
         4.04805951e-02, -3.42860967e-02, -1.93881076e-02,
         6.61234036e-02,  6.01589493e-02,  1.09370500e-02,
        -5.38625428e-03,  1.44580016e-02,  9.25430357e-02,
        -3.14563885e-02, -1.84351895e-02,  9.91874654e-03,
        -1.85574684e-02,  1.31280452e-03,  2.26234351e-05,
         2.02734210e-03,  2.75256690e-02, -4.81927022e-02,
         5.42825423e-02, -7.32066482e-02,  4.88667041e-02,
         4.98490445e-02, -9.01141018e-03, -4.68905717e-02,
        -4.25887033e-02, -8.19523707e-02,  3.87105830e-02,
         7.85502642e-02,  1.46077184e-32,  1.66707058e-02,
         5.25493808e-02, -1.82448979e-02, -1.26685752e-02,
         6.52837530e-02, -2.11777352e-02, -4.06323001e-02,
         4.14947644e-02, -2.48362310e-02, -1.33068832e-02,
        -5.46753965e-02, -5.99112886e-04, -4.89246938e-03,
        -6.27359822e-02, -3.84878144e-02, -6.13543764e-02,
         8.27405304e-02,  2.34380439e-02, -8.63089506e-03,
         1.31002869e-02,  6.44215122e-02, -4.41361293e-02,
        -6.98632821e-02, -7.36060217e-02, -4.33264188e-02,
         6.96524838e-03, -5.05956896e-02, -1.60912015e-02,
        -5.66793121e-02,  3.35456640e-03,  5.34114949e-02,
         2.47761197e-02, -1.47986244e-02, -2.93242894e-02,
         7.30228424e-02, -1.86833516e-02,  8.13136771e-02,
        -2.69967746e-02, -5.68056516e-02, -6.59388676e-02,
        -5.95392985e-03,  2.85312831e-02, -7.85358027e-02,
        -2.76697101e-03, -3.26468050e-03, -9.28333327e-02,
        -7.27363005e-02, -3.31903733e-02,  1.01411290e-01,
         9.79881808e-02, -9.78740677e-02,  1.98668279e-02,
         2.38836538e-02, -1.81672927e-02, -3.73709351e-02,
         1.96546479e-03,  6.34425730e-02,  1.18271522e-02,
        -1.12040918e-02, -3.87316719e-02,  9.32424441e-02,
         4.26635146e-03, -1.66872758e-02, -6.87463805e-02,
         1.55119635e-02, -4.97755259e-02,  3.34492698e-02,
         8.00032169e-02,  2.12282240e-02,  1.34581879e-01,
        -2.30729822e-02,  5.53859472e-02,  3.07557881e-02,
        -2.93905791e-02,  2.31905598e-02, -9.34307426e-02,
         7.58034587e-02, -5.21205924e-03, -5.14523461e-02,
         3.32688838e-02,  3.67963500e-02, -1.06450431e-02,
         1.01634767e-02, -2.07650270e-02, -5.85518815e-02,
         4.79328744e-02,  2.13694163e-02,  8.76213014e-02,
         3.35499877e-03, -3.80336344e-02, -1.81205310e-02,
         6.87439553e-03,  5.15879095e-02, -4.75599058e-02,
        -6.12065196e-02, -1.45483677e-32,  4.12797881e-03,
         4.59634745e-03, -5.63900694e-02,  4.32464620e-03,
        -1.09446363e-03,  9.31951962e-03, -2.20269207e-02,
         5.79564422e-02, -1.44787626e-02,  4.64155413e-02,
         1.43542916e-01, -6.89755902e-02,  6.09631427e-02,
        -8.93743709e-02,  2.40918938e-02,  2.06010342e-02,
        -2.82416232e-02, -6.48316070e-02,  5.64795695e-02,
        -7.48341996e-03, -3.52057591e-02,  8.51060823e-02,
         1.30359745e-02,  2.02258509e-02, -1.44390929e-02,
        -4.63718809e-02,  1.77209787e-02,  1.59106050e-02,
        -9.51009318e-02, -3.54527459e-02,  2.08695810e-02,
         3.84385465e-03, -8.77918601e-02,  6.44575804e-02,
         1.44170495e-02,  3.84729356e-03,  4.70991619e-02,
         4.94661406e-02,  1.53861968e-02, -2.59579085e-02,
         9.10895243e-02,  1.83307473e-02, -5.89207113e-02,
         2.51992904e-02, -3.30373943e-02,  8.23345259e-02,
         1.74792111e-02,  6.48047403e-02, -1.19673656e-02,
        -3.31777968e-02,  3.00177634e-02,  3.54220122e-02,
        -1.39624570e-02,  6.69272169e-02,  3.87919806e-02,
         6.06917106e-02,  1.17967324e-03, -2.38786265e-02,
        -1.26930416e-01,  1.13847200e-02,  1.59290396e-02,
        -1.29426625e-02, -8.63247663e-02,  8.53657164e-03,
         6.03760667e-02,  1.51122576e-02, -1.19132347e-01,
         1.15235336e-02,  5.97089082e-02, -3.93346585e-02,
         1.55673549e-02,  1.04602035e-02, -4.72456254e-02,
        -2.59243306e-02,  9.98529978e-03,  3.07146627e-02,
        -7.14843720e-02,  6.98957639e-03, -1.55132441e-02,
         2.18863934e-02, -2.78145541e-02,  6.92733005e-02,
        -2.75903307e-02,  2.62429044e-02,  3.52563225e-02,
        -4.26420346e-02,  7.46361562e-04,  6.59866929e-02,
        -5.15105799e-02, -3.58433574e-02, -6.53454335e-03,
        -2.75858659e-02, -1.00125462e-01,  7.83325657e-02,
        -1.45799201e-02, -6.18457676e-08,  2.00325046e-02,
         6.59785867e-02, -2.04702727e-02,  1.64043885e-02,
         7.63001516e-02,  7.32182637e-02,  5.65794855e-03,
        -6.97731739e-04, -3.63796577e-03,  6.02394305e-02,
        -3.27187628e-02, -6.45838454e-02, -5.97952940e-02,
        -1.76695120e-02,  6.10141922e-03, -5.63484570e-03,
        -1.22972235e-01,  6.35818839e-02, -2.19432414e-02,
        -1.16406478e-01,  2.34365351e-02, -7.23524839e-02,
         2.31774375e-02, -6.55987188e-02, -7.42682591e-02,
         2.60145608e-02,  3.59757878e-02,  7.68433064e-02,
        -3.08057535e-02, -2.34794132e-02, -6.30426630e-02,
        -3.62157263e-02, -1.03560034e-02, -4.75602038e-02,
        -2.87522543e-02,  2.96401326e-02, -5.26895234e-03,
         5.67889996e-02, -3.74486903e-03,  3.09611876e-02,
         3.48227248e-02,  3.78607363e-02,  2.10155733e-02,
         2.70691551e-02,  5.25520667e-02,  7.16229379e-02,
        -5.53757604e-03,  4.01094146e-02,  5.16276099e-02,
        -2.67314520e-02,  5.94223477e-02, -4.29223888e-02,
        -1.19760847e-02,  3.05985902e-02, -7.40331858e-02,
         1.84221938e-02, -8.64863582e-03, -8.83557945e-02,
        -5.91983944e-02, -1.00866026e-04,  1.12913705e-01,
         4.57789237e-03, -4.25971188e-02,  3.22619989e-03],
       [ 8.04573391e-03, -3.57392319e-02,  4.93874028e-02,
        -7.19186151e-03,  6.17681711e-04, -9.05684605e-02,
         5.75595275e-02, -4.39446084e-02,  1.74751170e-02,
         5.21202870e-02, -4.62332182e-02,  2.49038953e-02,
         4.80810888e-02,  6.86636493e-02,  3.56146656e-02,
         3.00088730e-02,  2.61450093e-02, -9.05241519e-02,
        -8.02173689e-02,  5.04851006e-02, -7.90870562e-02,
        -1.76852068e-03, -2.48927847e-02,  9.02152732e-02,
         5.83698181e-03, -6.91070855e-02, -6.67965636e-02,
        -6.99113635e-03, -1.04566023e-01, -2.66474169e-02,
         3.05640213e-02,  2.02933885e-02,  2.25454811e-02,
        -4.22686618e-03,  1.11173606e-02,  6.78261518e-02,
         1.06074074e-02,  7.56635591e-02, -8.22777748e-02,
         8.45730677e-03, -6.97612241e-02, -4.21973839e-02,
        -1.05674425e-02,  2.23672949e-02,  5.64497039e-02,
         8.16500932e-03,  1.09344050e-01,  3.16564664e-02,
        -1.76923666e-02, -3.21071297e-02, -3.39975916e-02,
        -4.91820916e-04,  3.72876017e-03,  2.83771548e-02,
        -1.28521482e-02, -1.07928505e-03, -6.32419214e-02,
         6.89900666e-02,  1.77270863e-02, -5.20959646e-02,
         8.28308053e-03,  5.45032471e-02, -5.42099513e-02,
        -4.53332923e-02, -4.07494046e-02, -2.82698646e-02,
         1.23605551e-02, -2.13816501e-02, -2.36266088e-02,
         1.25318076e-02, -2.37170830e-02,  3.97411510e-02,
        -1.24362230e-01,  7.60625526e-02,  5.50833605e-02,
         8.28216597e-02,  2.97118966e-02, -1.84067488e-02,
        -1.96194816e-02,  5.54318987e-02, -3.49143818e-02,
        -4.14678305e-02, -3.37047577e-02,  7.31324479e-02,
         4.41836566e-02,  2.55246796e-02, -8.26408248e-03,
        -1.07323704e-02, -4.26243581e-02, -2.84963404e-03,
         7.38559216e-02,  2.27768086e-02,  7.15384493e-04,
         4.36011963e-02,  5.09079844e-02,  6.38482273e-02,
        -2.73155440e-02, -6.55021966e-02, -7.69265443e-02,
         3.55171300e-02,  9.60494131e-02,  2.18195487e-02,
         1.20155104e-02, -1.17863361e-02, -4.57927259e-03,
        -8.58035032e-03,  3.37150171e-02,  2.31918246e-02,
        -7.58325383e-02, -5.23878708e-02,  4.53934111e-02,
        -3.80785502e-02, -3.34905125e-02,  9.20352936e-02,
         2.87688747e-02, -3.33817340e-02, -1.95854413e-03,
        -3.04582034e-04, -1.70499235e-02,  2.85335481e-02,
        -8.81096497e-02, -4.02253084e-02, -4.00093757e-02,
        -1.03193093e-02, -2.51968242e-02,  2.14092638e-02,
         1.31045282e-01, -5.29635189e-34, -1.09651700e-01,
         1.29811810e-02,  5.92659228e-03,  4.73506525e-02,
        -8.60294234e-03, -3.67089361e-02,  3.05214990e-02,
         5.53066470e-02, -4.71985191e-02, -1.25118969e-02,
        -1.15366392e-01,  9.08000302e-03,  1.07346520e-01,
        -4.94735017e-02, -1.34290894e-02, -4.61562127e-02,
         2.45320499e-02,  9.45082307e-03,  2.04323512e-02,
        -3.99918780e-02, -4.67826165e-02,  2.21171286e-02,
        -4.58186679e-02, -8.13272223e-03, -7.65669998e-03,
         1.92284361e-02,  4.85845394e-02, -2.55903304e-02,
         1.61545025e-03, -1.37180313e-02,  9.67306644e-03,
         7.36415759e-03,  1.14088571e-02,  1.28853485e-01,
         7.71834981e-03,  7.06362501e-02,  2.54452154e-02,
         4.06523831e-02,  2.44039688e-02,  1.43776750e-02,
        -6.00932650e-02,  7.38180354e-02, -2.44700704e-02,
         8.98901597e-02,  3.17052007e-03,  1.01834476e-01,
         4.17742059e-02, -5.95177822e-02, -3.23181264e-02,
         3.80938686e-02,  1.21155037e-02, -4.07834314e-02,
         2.84823086e-02,  4.90988642e-02, -9.35704447e-03,
         6.50073886e-02,  7.23532215e-02, -1.67793203e-02,
        -8.22416041e-03, -1.61573309e-02,  5.96225336e-02,
        -3.36083658e-02,  2.12108325e-02, -6.06090575e-02,
         1.54377654e-01, -7.24145845e-02, -3.77272852e-02,
        -3.26890238e-02, -1.80381408e-03, -1.01960255e-02,
        -1.60678616e-03, -6.91846684e-02,  8.28445256e-02,
         9.88839939e-02,  3.45468754e-03, -9.90247577e-02,
        -3.52826901e-02, -7.13178962e-02, -4.96000126e-02,
        -3.43954973e-02, -8.13042298e-02,  4.81448062e-02,
         5.00684232e-03, -2.21499782e-02, -5.60056306e-02,
         1.00067323e-02, -3.59794013e-02,  1.06184363e-01,
        -4.54196259e-02,  7.16393664e-02, -2.36773230e-02,
         9.98144783e-03,  2.73601897e-02,  1.05985448e-01,
         4.60163318e-02,  9.59029178e-34, -1.12306938e-01,
         2.78912298e-02, -3.35901007e-02,  5.39242588e-02,
        -2.22291648e-02,  1.53769413e-02,  3.10411267e-02,
         3.39011289e-02,  7.43166879e-02,  3.42471078e-02,
        -3.35054263e-03, -2.05350760e-02, -3.62370014e-02,
         2.29334123e-02, -3.01992334e-02, -1.00819916e-01,
         3.29193994e-02,  6.77542984e-02,  1.35645326e-02,
        -5.20545198e-03, -6.58158362e-02,  9.54550430e-02,
        -1.34038636e-02,  1.53885726e-02, -7.22936094e-02,
         9.67835709e-02, -8.08119401e-02, -4.53453325e-03,
        -6.42011836e-02, -4.99278381e-02,  4.64197919e-02,
         2.21341085e-02,  3.13109346e-02,  9.13568586e-02,
        -4.61119786e-02, -1.02761090e-01,  3.04415952e-02,
         5.09876348e-02,  6.70141056e-02,  1.04042655e-02,
         1.63533464e-02,  3.92030887e-02,  2.17154063e-02,
         5.36603145e-02,  3.62809673e-02, -4.22140248e-02,
        -2.47226637e-02,  1.90311801e-02,  3.61724198e-02,
         6.37021065e-02, -3.21581750e-03, -8.50390270e-03,
         3.94655317e-02,  9.02656000e-03,  1.93095729e-02,
         6.60718009e-02,  1.02694947e-02, -4.43853885e-02,
        -1.56523455e-02, -1.55714592e-02,  1.32904444e-02,
        -1.16108339e-02,  4.21832167e-02, -5.44777103e-02,
         1.29237190e-01, -2.25756615e-02,  5.26203848e-02,
        -1.58437025e-02,  9.33165625e-02,  6.38025859e-03,
        -9.36161820e-03, -6.08876050e-02, -3.27307768e-02,
        -3.44816446e-02,  3.29974107e-02, -4.79391702e-02,
        -9.81300697e-02,  2.91164946e-02, -2.70903353e-02,
         1.81867406e-02, -1.73860192e-02, -4.40371446e-02,
        -7.97001943e-02,  3.01647130e-02, -6.35260493e-02,
         1.25963474e-02,  8.50250721e-02, -4.58910540e-02,
         5.81017397e-02, -2.71002203e-02,  8.42775926e-02,
        -4.09972928e-02, -3.37655954e-02,  1.02088209e-02,
        -2.54192818e-02, -1.40610323e-08,  4.94446494e-02,
        -9.04357061e-02, -6.06710017e-02,  8.29528943e-02,
        -3.29032876e-02,  4.14910577e-02,  9.99591406e-03,
         6.96135825e-03,  3.99230001e-03, -3.24333534e-02,
        -3.14657390e-02, -5.33160940e-02, -3.80912945e-02,
         1.62077043e-02,  2.45778374e-02, -7.26419389e-02,
        -6.56893402e-02, -8.23131651e-02, -8.00500885e-02,
        -5.36649525e-02,  5.60894459e-02, -1.10913105e-02,
         9.62130027e-04, -1.22690290e-01, -5.13836667e-02,
         9.96703096e-03,  1.00696282e-02,  1.07073061e-01,
         1.19758174e-02,  1.00423563e-02, -6.28261641e-02,
        -7.49696866e-02, -6.34075701e-03, -2.72201318e-02,
        -1.28096193e-01, -2.62459964e-02, -1.81464311e-02,
        -9.85359997e-02, -3.02990600e-02, -4.02615182e-02,
         9.94290784e-02,  5.35999909e-02,  2.74899527e-02,
        -5.53683145e-03,  8.43571201e-02,  8.35161880e-02,
         3.74305062e-02,  7.11937174e-02,  2.98902709e-02,
         2.32728720e-02, -3.62112485e-02,  6.20539747e-02,
         2.15148162e-02,  5.19732237e-02,  1.45337647e-02,
        -4.60966453e-02,  5.02553992e-02, -7.27027580e-02,
         2.92778797e-02,  5.62663153e-02, -3.86354961e-02,
         1.53831542e-02, -6.23094887e-02, -2.77466476e-02]], dtype=float32)

In [36]:
x=filtered_embeddings
y=df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
report = classification_report(y_test,y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [37]:
import joblib
joblib.dump(clf, 'models/log_classifier.joblib')

['models/log_classifier.joblib']